[package]
name = "mergle"
version = "0.1.0"
authors = ["Ben Weinstein-Raun <root@benwr.net>", "Jennifer Blight <jgblight@gmail.com>"]
edition = "2018"

[profile.release]
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
bromberg_sl2 = "0.4"

[dev-dependencies]
quickcheck = "0.9"
